name = "temp-email"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true

crons = [ "0 1 * * *" ]

[vars]
PREFIX = ""
ADMIN_PASSWORDS = ["aabbccdd"]
DEFAULT_DOMAINS = ["bcd.indevs.in"] # domain name for no role users
DOMAINS = ["bcd.indevs.in"] # all domain names
JWT_SECRET = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
BLACK_LIST = ""
ENABLE_USER_CREATE_EMAIL = false
ENABLE_USER_DELETE_EMAIL = false
ENABLE_AUTO_REPLY = false

[[d1_databases]]
binding = "TEMP-EMAIL-DB"
database_name = "temp-email-db"
database_id = "aaaa-bbbb-cccc-dddd-ffffffffffff"

[[kv_namespaces]]
binding = "TEMP-EMAIL-KV"
id = "ggggggggggggggggggggggg"
